/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NGramClassification;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author falmuqhim
 */
public class DSForm extends javax.swing.JFrame {

    JFileChooser DSfileChooser;
    JFileChooser directoryChooser;
    File sequenceFile;
    File sequenceFile1;
    File DSdirectory;
    File DSdirectory1;

    /**
     * Creates new form MainForm
     */
    public DSForm() {
        initComponents();
        sequenceFile = null;
        DSdirectory = null;
        sequenceFile1 = null;
        DSdirectory1 = null;

        DSfileChooser = new JFileChooser();
        directoryChooser = new JFileChooser();
        directoryChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        DSfileChooser.addChoosableFileFilter(new Filter());
        DSfileChooser.setAcceptAllFileFilterUsed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sequenceFileTF = new javax.swing.JTextField();
        outputDirectoryTF = new javax.swing.JTextField();
        sequenceBTN = new javax.swing.JButton();
        outputBTN = new javax.swing.JButton();
        runBTN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sequenceFileTF1 = new javax.swing.JTextField();
        outputDirectoryTF1 = new javax.swing.JTextField();
        sequenceBTN1 = new javax.swing.JButton();
        outputBTN1 = new javax.swing.JButton();
        runBTN1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        startTF = new javax.swing.JTextField();
        endTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));

        jPanel1.setBackground(jPanel2.getBackground());
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Remove Duplicate"));

        jLabel1.setText("Sequence File");

        jLabel2.setText("Output Directory");

        sequenceFileTF.setEnabled(false);

        outputDirectoryTF.setEnabled(false);

        sequenceBTN.setText("Choose ...");
        sequenceBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DSForm.this.actionPerformed(evt);
            }
        });

        outputBTN.setText("Select ...");
        outputBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DSForm.this.actionPerformed(evt);
            }
        });

        runBTN.setText("Run");
        runBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sequenceFileTF, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(outputDirectoryTF))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sequenceBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(runBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sequenceFileTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sequenceBTN))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(outputDirectoryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(runBTN)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel3.setBackground(jPanel2.getBackground());
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Remove By Range"));

        jLabel3.setText("Sequence File");

        jLabel4.setText("Output Directory");

        sequenceFileTF1.setEnabled(false);

        outputDirectoryTF1.setEnabled(false);

        sequenceBTN1.setText("Choose ...");
        sequenceBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DSForm.this.actionPerformed(evt);
            }
        });

        outputBTN1.setText("Select ...");
        outputBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DSForm.this.actionPerformed(evt);
            }
        });

        runBTN1.setText("Run");
        runBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runBTN1ActionPerformed(evt);
            }
        });

        jLabel5.setText("<= Sequence <=");

        startTF.setText("20");

        endTF.setText("100");

        jLabel6.setText("Sequence Range:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(sequenceFileTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(outputDirectoryTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(startTF, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(endTF, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(runBTN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outputBTN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sequenceBTN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sequenceFileTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sequenceBTN1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(outputDirectoryTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputBTN1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(startTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(endTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(runBTN1))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == sequenceBTN || evt.getSource() == sequenceBTN1) {
            int returnVal = DSfileChooser.showDialog(this, "Choose");
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                if (evt.getSource() == sequenceBTN) {
                    sequenceFile = DSfileChooser.getSelectedFile();
                    sequenceFileTF.setText(sequenceFile.getName());
                }
                if (evt.getSource() == sequenceBTN1) {
                    sequenceFile1 = DSfileChooser.getSelectedFile();
                    sequenceFileTF1.setText(sequenceFile1.getName());
                }
            } else {
                System.out.println("closed by user");
            }
        }
        if (evt.getSource() == outputBTN || evt.getSource() == outputBTN1) {
            int returnVal = directoryChooser.showDialog(this, "Select");
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                if (evt.getSource() == outputBTN) {
                    DSdirectory = directoryChooser.getSelectedFile();
                    outputDirectoryTF.setText(DSdirectory.getAbsolutePath());
                }
                if (evt.getSource() == outputBTN1) {
                    DSdirectory1 = directoryChooser.getSelectedFile();
                    outputDirectoryTF1.setText(DSdirectory1.getAbsolutePath());
                }
            } else {
                System.out.println("closed by user");
            }
        }
    }//GEN-LAST:event_actionPerformed

    private void runBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runBTNActionPerformed
        // TODO add your handling code here:
        if (sequenceFile == null || DSdirectory == null) {
            JOptionPane.showMessageDialog(this,
                    "Please select the sequence file and the directory for the "
                    + "output to run the program.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        DistinctSequence ds = new DistinctSequence();
        int numberOfDuplicate = ds.removeDuplicate(sequenceFile.getPath(), DSdirectory.getPath() + "/");
        JOptionPane.showMessageDialog(this, numberOfDuplicate + " have been removed from the sequence", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_runBTNActionPerformed

    private void runBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runBTN1ActionPerformed
        // TODO add your handling code here:
        if (sequenceFile1 == null || DSdirectory1 == null) {
            JOptionPane.showMessageDialog(this,
                    "Please select the sequence file and the directory for the "
                    + "output to run the program.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        String regex = "\\d+";
        if (!startTF.getText().matches(regex) || startTF.getText().startsWith("-")) {
            JOptionPane.showMessageDialog(this,
                    "Please enter a valid value for the start of the range", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!endTF.getText().matches(regex) || endTF.getText().startsWith("-")) {
            JOptionPane.showMessageDialog(this,
                    "Please enter a valid value for the end of the range", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        DistinctSequence ds = new DistinctSequence();
        int numberOfRemoved = ds.acceptByRange(sequenceFile1.getPath(), 
                DSdirectory1.getPath() + "/", Integer.parseInt(startTF.getText()), Integer.parseInt(endTF.getText()));
        JOptionPane.showMessageDialog(this, numberOfRemoved + " have been removed from the sequence", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_runBTN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DSForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField endTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton outputBTN;
    private javax.swing.JButton outputBTN1;
    private javax.swing.JTextField outputDirectoryTF;
    private javax.swing.JTextField outputDirectoryTF1;
    private javax.swing.JButton runBTN;
    private javax.swing.JButton runBTN1;
    private javax.swing.JButton sequenceBTN;
    private javax.swing.JButton sequenceBTN1;
    private javax.swing.JTextField sequenceFileTF;
    private javax.swing.JTextField sequenceFileTF1;
    private javax.swing.JTextField startTF;
    // End of variables declaration//GEN-END:variables
}
